language: java
jdk:
- oraclejdk8
- oraclejdk7

before_install:
  - wget https://github.com/Cnly/Crafter/archive/1.2.1.tar.gz -O crafter.jar
  - tar -xvf crafter.jar
  - cd Crafter-1.2.1/Crafter
  - mvn clean install
  - cd ../..
